# Generated by Django 4.2.2 on 2023-07-15 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('copy', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('attendance', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('note', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('lecture', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('average', models.FloatField()),
            ],
        ),
    ]
