# Generated by Django 4.2.2 on 2023-07-16 00:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_academician_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('name', models.CharField(max_length=264)),
                ('link', models.URLField()),
                ('class_year', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('academician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.academician')),
            ],
        ),
    ]
