# Generated by Django 4.2.2 on 2023-07-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='link',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(choices=[('1', 'MEDICAL BIOLOGY'), ('2', 'MEDICAL BIOCHEMISTRY'), ('3', 'BIOPHYSICS'), ('4', 'PHYSIOLOGY'), ('5', 'MEDICAL GENETICS'), ('6', 'HİSTOLOGY'), ('7', 'ANATOMY'), ('8', 'MICRO'), ('9', 'IMMUN'), ('10', 'PATHOLOGY'), ('11', 'BIOIST'), ('12', 'PED'), ('13', 'PHARMACOLOGY'), ('14', 'INTERNAL MEDICINE'), ('15', 'ANATOMY'), ('16', 'UROLOGY'), ('17', 'RADIOLOGY'), ('18', 'OBSTETRICS and GYNECOLOGY'), ('19', 'CHILD HEALTH'), ('20', 'GENERAL SURGERY'), ('21', 'ORTHOPEDICS'), ('22', 'DERMATOLOGY'), ('23', 'MED. GENETICS'), ('24', 'NEUROLOGY'), ('25', 'NEUROSURGERY'), ('26', 'CARDIO'), ('27', 'INFECTIOUS DIS'), ('28', 'PUBLIC HEALTH'), ('29', 'BASIC STATISTICS')], default='1', max_length=20),
        ),
    ]
