# Generated by Django 4.2.2 on 2023-07-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_temp_remove_lesson_link_alter_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='copy_or_note',
            field=models.CharField(choices=[('copy', 'Çıkmış'), ('note', 'Ders Notu')], default='1', max_length=20),
        ),
    ]
