# Generated by Django 4.2.2 on 2023-07-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lesson_copy_or_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='copy_or_note',
            field=models.CharField(choices=[('copy', 'Çıkmış'), ('note', 'Ders Notu')], default='copy', max_length=20),
        ),
    ]
