# Generated by Django 4.2.2 on 2023-09-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_lesson_copy_or_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_year',
            field=models.SmallIntegerField(default=2000),
            preserve_default=False,
        ),
    ]
